### ISSUE TITLE
 No module named 'django.utils.six'

### ISSUE THREAD

**Issue by landerover** [lehins/django-smartfields#22]
This module has been removed from django 3.

As reported here:
[https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis]

For this reason i can't use this library currently.

**Comment by lehins** [comment]
Damn, forgot to make a release. I'll try make one over the weekend. For now try using master branch in this repo, since this issue should have been fixed in one of the recent PRs.21:55, January 23, 2020, RedKiller <notifications@github.com>:This module has been removed from django 3.
As reported here:
[https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis]
For this reason i can't use this library currently.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by lehins** [comment]
[django-smartfields-1.1.1](https://pypi.org/project/django-smartfields/) is now on pypi. Let me know if you are still having problems with Django-3
Thanks to @suhaibroomy for fixing it.
