### ISSUE TITLE
ModuleNotFoundError: No module named 'smartfields'

### ISSUE THREAD

**Issue by MaqOwais** [lehins/django-smartfields#23]

**Comment by lehins** [comment]
Looks like a setup error on your part, especially considering that the "not found" module is right here [smartfields](https://github.com/lehins/django-smartfields/blob/master/smartfields/__init__.py). 

Quite a bit more information would be needed to turn it into a bug report, otherwise I'll be closing this ticket pretty soon.

**Comment by lehins** [comment]
Closing as no more information was provided.
